language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=jen -m unittest
after_success:
  - coveralls
